### ISSUE TITLE
Build Fail and its Workaround

### ISSUE THREAD

**Issue by bretonio** [onedevstudio/starter-kit#1]
Building your starter kit &mdash; nice! &mdash; failed on Debian with Node 11.6.0 and NPM 3.10.3 

<blockquote>gulp[9952]: ../src/node_contextify.cc:628:static void node::contextify::ContextifyScript::New(const v8::FunctionCallbackInfo<v8::Value>&): Assertion `args[1]->IsString()' failed.
 1: 0x948d20 node::Abort() [gulp]
 2: 0x948db5  [gulp]
 3: 0x946d8e node::contextify::ContextifyScript::New(v8::FunctionCallbackInfo<v8::Value> const&) [gulp]
 4: 0xb9698f  [gulp]
 5: 0xb98952 v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) [gulp]
 6: 0xd254e64fb5d 
Aborted</blockquote>

I downgraded  Node with the retro `nvm use 6.5.0`  and she built for me.

**Comment by nandomoreirame** [comment]
Hi @bretonio 🤘 
I am building version 2.0 of this project using Gulp v4.

thanks for reporting.

**Comment by nandomoreirame** [comment]
@bretonio Starter Kit 2.0 has arrived!
Now using Gulp 4 with Webpack, Pug and SASS 🤘
